# Generated by Django 4.1.6 on 2023-02-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_peliculas', '0002_director_genre_movie_delete_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='birth_date',
        ),
    ]
