# Generated by Django 4.1.6 on 2023-02-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_peliculas', '0003_remove_director_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Colocar el resumen de la pelicula'),
        ),
    ]
